### ISSUE TITLE
[Bug] effret Portfolio shows the same weight regardless of return

### ISSUE THREAD

**Issue by minhhoang1023** [GamestonkTerminal/GamestonkTerminal#1376] opened 2022-02-16 05:53 UTC
**Describe the bug**
I was trying different return yet the portfolio weights stay the same in all cases.

<img width="717" alt="image" src="https://user-images.githubusercontent.com/40023817/154204546-6078f5f5-e431-4a94-bfae-8d1177fb1d40.png">

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior
- Ticker chosen: AAPL, TSLA, PYPL
- effret 0.05
- effret 0.1
- effret 0.2

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac Catalina
- Python version: 3.9

**Additional context**
Add any other information that you think could be useful for us.

**Comment by jmaslek** [comment] 2022-02-16 13:41
Think this is a feature not a bug:  if you look at the efficient frontier I think it paints a picture as to why the weights kind of stay the same.


![efret](https://user-images.githubusercontent.com/18151143/154276166-ec5013c4-91f6-4718-a801-ae608dea6d33.png)

**Comment by jmaslek** [comment] 2022-02-17 19:39
Closing since this is not a bug

**Closed by jmaslek** 2022-02-17 19:39 UTC
