### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by bigeaz** [GamestonkTerminal/GamestonkTerminal#638] opened 2021-08-03 05:26 UTC
**Describe the bug**
"No module named 'sentipy.sentipy'"
**To Reproduce**
Steps(from the start) and commands to reproduce the behavior
When I run "python terminal.py" in the cmd screen I get this error. 

**Screenshots**
![sentipy sentipy error](https://user-images.githubusercontent.com/88364393/127962628-6dd5d200-7108-4231-8693-8cf38ee176c7.PNG)

![sentipy sentipy error install](https://user-images.githubusercontent.com/88364393/127963214-b98442eb-0c71-478b-a28b-ad469394169a.PNG)

**Desktop (please complete the following information):**
 - OS: [e.g. Mac Sierra]
 - Python version [e.g. 3.6.8]
Windows 10 Pro. Python 3.8.10
**Additional context**
Add any other information that you think could be useful for us.

**Comment by DidierRLopes** [comment] 2021-08-03 08:39
Did you do poetry install or pip install -r requirements.txt?

I think you can do "pip install sentiment-investor" to fix this. Let me know if it worked!

**Comment by dancost** [comment] 2021-08-03 08:47
I see 2 problems here:
1. You're trying to install sentipy.sentypy - pip install sentipy should be enough.
2. You're doing pip install _after_ deactivating the "gst" virtual environment. Why?

This looks you did not "pip install -r requirements.txt" while "gst" virtual env was active, and this is causing your issue.

This is not a bug, in my opinion.

**Comment by jmaslek** [comment] 2021-08-03 14:22
So I will slightly piggyback. 

1) sentipy is the package.  It actually looks like an alias for sentiment-investor (https://github.com/sentimentinvestor/sentipy)  sentipy. sentipy imports `sentipy` from that package (yes-kind of redundant).  

The previous comment nailed it.  You need to do your installs while the environment is activated or else when you activate the env, it has no idea what you just did.

So while you are activated, `conda activate gst`, you should be able to run `poetry install` (preferred) or `pip install -r requirements.txt`.

Going to close this.  Feel free to reopen if you have more issues

**Closed by jmaslek** 2021-08-03 14:22 UTC
Labels: type:bug

**Comment by bigeaz** [comment] 2021-08-04 01:41
> Did you do poetry install or pip install -r requirements.txt?
> 
> I think you can do "pip install sentiment-investor" to fix this. Let me know if it worked!

Thank you this worked!
